sonar.projectKey=online-boutique
sonar.projectName=Online Boutique
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/*_test.go,**/*.test.js,**/vendor/**,**/node_modules/**
sonar.java.binaries=.