grafana:
  env:
    GF_AUTH_GITHUB_ENABLED: "true"
    GF_AUTH_GITHUB_ALLOW_SIGN_UP: "true"
    GF_AUTH_GITHUB_SCOPES: "user:email,read:org"
    GF_AUTH_GITHUB_AUTH_URL: "https://github.com/login/oauth/authorize"
    GF_AUTH_GITHUB_TOKEN_URL: "https://github.com/login/oauth/access_token"
    GF_AUTH_GITHUB_API_URL: "https://api.github.com/user"
    GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: "Vivixell"
    GF_SERVER_ROOT_URL: "https://grafana.vicops.xyz"

  envValueFrom:
    GF_AUTH_GITHUB_CLIENT_ID:
      secretKeyRef:
        name: grafana-github-oauth
        key: client_id
    GF_AUTH_GITHUB_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-github-oauth
        key: client_secret

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: "vicops-shared-alb"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:021104859097:certificate/43512578-fa24-495f-b805-77cb2f3b5fae
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
    hosts:
      - grafana.vicops.xyz
    path: /
    pathType: Prefix